### ISSUE TITLE
YAML variables marked as invalid in `catalog.yml`

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/vscode-kedro#148]
> The problem also applies to YAML anchors/aliases:

```YAML
_spark_parquet: &spark_parquet
  type: spark.SparkDataset
  save_args:
    mode: overwrite
```

<img width="270" alt="img" src="https://github.com/kedro-org/vscode-kedro/assets/84588078/eefea0a7-3f33-4a8e-9bd4-37afa9b1af3a">

_Originally posted by @michal-mmm in https://github.com/kedro-org/vscode-kedro/issues/5#issuecomment-2132839659_
