### ISSUE TITLE
Kedro extension warns about problem in catalog entry incorrectly

### ISSUE THREAD

**Issue by Acomar0** [kedro-org/vscode-kedro#174]
## Description
When using dataset factory patterns plus a reference to a conf .yml file in the dataset args the extension recognizes this reference as another factory pattern, thus warning about a problem:
```
Keys used in the configuration {'{globals:columns}'} should present in the dataset factory pattern name
``` 
## Steps to Reproduce
1. Define parameters in conf file
 ```
columns:  [
            "column1",
            "column2"
          ]
 ```
3. Define a dataset entry with factory patterns in the catalog.yml
 ```
data_{var1}_{var2}:
  type: pandas.ParquetDataset
  filepath: /my/path/{var1}/{var2}/data.parquet
  load_args:
    columns: "${globals:columns}"
 ```
5. Expected Result
Data is ingested by the pipeline without warnings

## Actual Result
Data is ingested but I get the warning:
 ```
Keys used in the configuration {'{globals:columns}'} should present in the dataset factory pattern name
``` 

## Your Environment

* Kedro version used (`pip show kedro` or `kedro -V`): 0.19.11
* Kedro extension version: 0.3.0
* Python version used (`python -V`): 3.11.4
* Operating system and version: Win11 Pro 22631.5039
